# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b95a7143d18e3b2a0ce106668de6991ea288cbf30df82903d0e005c9a31f2e9c6eddb7faf3cac51aada0642e4f5c42ad5cdccf27c91bea253c2d64bd647f535e

test:
  secret_key_base: d0aee266289e7b2e869c70a5d51129f2ed80ad642a50e62356c3da364f08f7499d24fb564ec97b30a5a84b40a3f1657f2a26eaea9de2ce6adf0691b1fcbbe263

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
